version: 0.0
os: linux
files:
  - source: AspNetCoreWebApplication/bin/release/netcoreapp3.1/
    destination: /home/ec2-user/aspnetcoreapp
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root

