version: 0.2
phases:
    install:
        runtime-versions:
          dotnet: 6.0
          nodejs: 18
    pre_build:
        commands:
            - dotnet restore WooDevOps.csproj
            - cd ClientApp ; npm ci ; cd ..
    build:
        commands:
            - dotnet publish -c release -o ./build_output WooDevOps.csproj
            - cd ClientApp ; npm run build ; cd ..
artifacts:
    files:
        - bin/**/*
        - ClientApp/dist/**/*
        - appspec.yml
        - scripts/**/*
